### ISSUE TITLE
Server crash loading Tribbles Deck Builder UI

### ISSUE THREAD

**Issue by andrewd18** [trekcc-ops/gemp-stccg#102] opened 2024-11-27 02:41 UTC
As seen on `main`, today. When I enter "Tribbles" in the Deck Builder UI prompt, it crashes with this error in the log file. The front-end seems to be acting normally otherwise.

```
02:37:45.562 [nioEventLoopGroup-3-1] ERROR com.gempukku.stccg.async.GempukkuHttpRequestHandler - Error response for /gemp-stccg-server/deck/stats
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.gempukku.stccg.common.CardDeck.getSubDeck(com.gempukku.stccg.common.filterable.SubDeck)" is null
	at com.gempukku.stccg.formats.DefaultGameFormat.validateDeckStructure(DefaultGameFormat.java:408) ~[web.jar:?]
	at com.gempukku.stccg.formats.DefaultGameFormat.validateDeck(DefaultGameFormat.java:298) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.HTMLUtils.getDeckValidation(HTMLUtils.java:174) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.DeckRequestHandler.getDeckStats(DeckRequestHandler.java:158) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.DeckRequestHandler.handleRequest(DeckRequestHandler.java:73) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.RootUriRequestHandler.handleRequest(RootUriRequestHandler.java:74) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:82) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:1) ~[web.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[web.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[web.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[web.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[web.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[web.jar:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by datanoh** [comment] 2024-11-27 19:44
@andrewd18 This is a good catch, but let's just ax the Tribbles deck builder UI for now and come back to it after MVP. The Tribbles game doesn't work right now anyway, so there's no benefit to making a Tribbles deck.

**Comment by datanoh** [comment] 2024-11-29 18:03
@andrewd18 Identified the cause of the NPE. Can fix it in the "Various UI cleanups" branch if you like, so we can close this issue.

**Comment by datanoh** [comment] 2024-12-15 21:31
Marking this as resolved. There have been some underlying changes to address it, and there will need to be more done before the Tribbles deck builder UI is usable anyway.

**Closed** 2024-12-15 21:31 UTC
Labels: bug, Java, DeckBuilder
